# Generated by Django 4.2.3 on 2023-08-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_cover_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_cover',
            field=models.ImageField(blank=True, upload_to='profile-covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile-pictures/%Y/%m/%d/'),
        ),
    ]
